#pragma once
// ============================================================================
//  GENERATED by Tools/License/make_codes.py - do not edit by hand.
//  Salted SHA-256 hashes of the valid serial numbers (the codes themselves are
//  not in the plug-in). 25 codes.
// ============================================================================
namespace dali::licensekeys
{
inline constexpr const char* kSaltHex = "88953fdb584fbdcb812f6207908ca74c";
inline constexpr const char* kHashes[] = {
    "88d93431685e90e7ed222a9c6ca0ebdbff91a59d4d32dcde601bf022ce18e558",
    "d71c82a28c3306445e8b41e217e555c645be01cdf06bf9c435d09a11682f5b95",
    "e08874008ff4dad742db0e8e506857717fbce7ffe12641b6cc5b5c8325eaeb67",
    "c176035bbb015d74df1aec87491c534f5782c89402a31c7bb9175a873ca3c48e",
    "7626eec6f92c90dc297ee64763d2a90e1ddc52862ff9b5c5612ce9c1da34ae79",
    "ce8e89528ffa15ec2be581ac97819993dd57c5057e34922f1797f23824a6e3b3",
    "c5b36bb33b36c63cb3bed336726510e31b983a6167ffd00a6426f144076f19e6",
    "cf8bc934a656d771b4b408791932e4e64e885feb36865640a36e4a69c9131121",
    "7f2b918cc2915b4570ae05e80a0bd281a3042733283ea8e303fd8451752fdc66",
    "505c5b234c14d42c1ebdba9cb80d26ca4ebf5a6762f8effd8796af37d8172b71",
    "6e2fcdc883f6028b30f5e562d192ca19a5e182deb42f496f92a92df68ea4d068",
    "946acadb82c3b55cc5c0e69cf08352c5367400b492299661c3f9e4f8e757549f",
    "dc7cd23c1ef88a2c9559461e3b4a86715d917e0ce1377a1b5f2ffb41ef9b708c",
    "8c5d3931f79b8ad1ed341b9d067d43357fe23d1cc11fc5ded42059a42e15f09f",
    "33885b556094799f9db5f69ea53090acd3403e1170625a852cac951d22733260",
    "6eb742524dca3b31464633d814bab9763e9e002cafdbc078435d9cb255a8dcdb",
    "e8a3ad918a424dbe6bed445b5b7d330336e5445970b8e67eaae4b6d5098348df",
    "069392e88ddced61bc3d76a147b1f0b9accf18416e88a67c8647be86e6e1a293",
    "dfa33cd2af9e50a89365c5bc33c4fe91d5068dfcfee1e68dfff3fab97273dcbf",
    "aeb576d1b238dedabc279f2752cbe66c90c0e49a8d4501644b828af4b61c557a",
    "a7a0cfb59d7ecbbd30d106015668ea4e6eedf6aad68a8f6daf4bfcd50ae7715c",
    "18778dd3dd256d7cab451d8e087e3cf2d8f3efc8f4b03299110fcd0d24205f9e",
    "3f632e3cd19f6f44d3c91c7d33fa49942b9d5c56afc428de16a80cf06d1b5654",
    "b8af7bace6515629ac145371fd8a838e7e0d7d38013877445b84fd40579ab468",
    "4213ebd9e75b633409aa914e4578b495e5ed8c740596c38fa7bf4c38ce1409eb"
};
} // namespace dali::licensekeys
