#!/usr/bin/env python3
"""
Dali Visual - serial numbers (fixed codes, checked offline).

The plug-in contains ONLY salted SHA-256 hashes of the codes (Source/Core/LicenseKeys.h),
never the codes themselves. Keep the printed codes private (NOT in a public repository).

  python3 Tools/License/make_codes.py --new 20            # first time: new salt + 20 codes
  python3 Tools/License/make_codes.py --add 10            # 10 more codes, same salt (old codes stay valid)
  python3 Tools/License/make_codes.py --revoke DALI-XXXX-XXXX-XXXX   # a leaked code stops working in the next build
  python3 Tools/License/make_codes.py --check DALI-XXXX-XXXX-XXXX    # is this code in the build?

After --new / --add / --revoke: rebuild (push to GitHub) so the new list is inside the plug-in.
"""
import argparse, hashlib, os, re, secrets, sys

HERE = os.path.dirname(os.path.abspath(__file__))
HEADER = os.path.normpath(os.path.join(HERE, "..", "..", "Source", "Core", "LicenseKeys.h"))
ALPHABET = "23456789ABCDEFGHJKLMNPQRSTUVWXYZ"          # no 0/O/1/I: easy to type

def normalise(code: str) -> str:
    s = re.sub(r"[^0-9A-Z]", "", code.upper())
    if s.startswith("DALI") and len(s) == 16:
        s = s[4:]
    return s

def digest(salt: bytes, code: str) -> str:
    return hashlib.sha256(salt + normalise(code).encode()).hexdigest()

def new_code() -> str:
    body = "".join(secrets.choice(ALPHABET) for _ in range(12))
    return "DALI-" + "-".join(body[i:i + 4] for i in range(0, 12, 4))

def read_header():
    if not os.path.exists(HEADER):
        return None, []
    text = open(HEADER, encoding="utf-8").read()
    salt = bytes.fromhex(re.search(r'kSaltHex\s*=\s*"([0-9a-f]+)"', text).group(1))
    hashes = re.findall(r'"([0-9a-f]{64})"', text)
    return salt, hashes

def write_header(salt: bytes, hashes):
    lines = ",\n".join(f'    "{h}"' for h in hashes)
    open(HEADER, "w", encoding="utf-8").write(f'''#pragma once
// ============================================================================
//  GENERATED by Tools/License/make_codes.py - do not edit by hand.
//  Salted SHA-256 hashes of the valid serial numbers (the codes themselves are
//  not in the plug-in). {len(hashes)} codes.
// ============================================================================
namespace dali::licensekeys
{{
inline constexpr const char* kSaltHex = "{salt.hex()}";
inline constexpr const char* kHashes[] = {{
{lines}
}};
}} // namespace dali::licensekeys
''')

def main():
    ap = argparse.ArgumentParser()
    g = ap.add_mutually_exclusive_group(required=True)
    g.add_argument("--new", type=int, metavar="N")
    g.add_argument("--add", type=int, metavar="N")
    g.add_argument("--revoke", metavar="CODE")
    g.add_argument("--check", metavar="CODE")
    a = ap.parse_args()
    salt, hashes = read_header()

    if a.new:
        if hashes and input("This replaces ALL existing codes (they stop working). Type YES: ") != "YES":
            sys.exit("cancelled")
        salt, hashes, codes = secrets.token_bytes(16), [], []
        for _ in range(a.new):
            c = new_code(); codes.append(c); hashes.append(digest(salt, c))
        write_header(salt, hashes)
        print("\n".join(codes))
    elif a.add:
        if salt is None: sys.exit("no LicenseKeys.h yet - use --new first")
        codes = []
        for _ in range(a.add):
            c = new_code(); codes.append(c); hashes.append(digest(salt, c))
        write_header(salt, hashes)
        print("\n".join(codes))
    elif a.revoke:
        h = digest(salt, a.revoke)
        if h not in hashes: sys.exit("that code is not in the build")
        hashes.remove(h); write_header(salt, hashes)
        print("revoked - rebuild to apply")
    else:
        print("VALID" if digest(salt, a.check) in hashes else "NOT VALID")

if __name__ == "__main__":
    main()
